### ISSUE TITLE
Retry also on initial connect

### ISSUE THREAD

**Issue by eiabea** [transcovo/bunyan-logstash-tcp#3]
Initializing the bunyan logger with this stream without a running logstash instance results in an unhandled error event

```
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:9999
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1195:14)
```
Maybe the retry function can also be applied on the error event? I wasn't able to handle the error event on my own.

**Comment by eiabea** [comment]
This already works, i just missed the
```
.on('error', console.log)
```
line...sorry!
