### ISSUE TITLE
how to deal with connection issue?

### ISSUE THREAD

**Issue by jzlocz** [transcovo/bunyan-logstash-tcp#4]
When logstash endpoint is not ready I got this and crash:

`Error: connect ENETUNREACH 192.168.20.85:5044
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14) 
error Command failed with exit code 1.`

Does anyone encounter similar problem? 
Is there any solution to avoid app crashing in this case?

**Comment by jzlocz** [comment]
`
bunyantcp.createStream({
            host: '127.0.0.1',
            port: 9998
        }).on('error', console.log)
`
example solved my problem
